name: Build

on:
  push:
    branches: [ main ]

jobs:         
  docker:
    name: Build docker ðŸ¬
    runs-on: ubuntu-latest
    steps:
      - name: Add SHORT_SHA env property with commit short sha
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-7`" >> $GITHUB_ENV
      - uses: actions/checkout@v2
      
      - name: Docker Login
        uses: docker/login-action@v2.0.0
        with:
          registry: klexhub.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build Docker image
        run: docker build . --tag klexhub.azurecr.io/waigel/reisswolf-exporter:${SHORT_SHA} --build-arg=GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD) --build-arg=GIT_COMMIT=${SHORT_SHA}
      - name: Push Docker image
        run: docker push klexhub.azurecr.io/waigel/reisswolf-exporter:${SHORT_SHA}
